#!/bin/bash
DEFAULT_CONF=tt-rss/config.php-dist
CONF=tt-rss/config.php

[[ -f "$CONF" ]] && echo "tt-rss already configured" && exit 0

sed -r 's|^(\s*define\('\''DB_TYPE'\'',).*$|\1 "$DB_TYPE");|;
				s|^(\s*define\('\''DB_NAME'\'',).*$|\1 "$DB_NAME");|;
				s|^(\s*define\('\''DB_HOST'\'',).*$|\1 "$DB_HOST");|;
				s|^(\s*define\('\''DB_PORT'\'',).*$|\1 "$DB_PORT");|;
				s|^(\s*define\('\''DB_USER'\'',).*$|\1 "$DB_USER");|;
				s|^(\s*define\('\''DB_PASS'\'',).*$|\1 "$DB_PASS");|;
				s|^(\s*define\('\''PHP_EXECUTABLE'\'',).*$|\1 "$(which php)");|;
				s|^(\s*define\('\''SELF_URL_PATH'\'',).*$|\1 "$SELF_URL_PATH");|;' "$DEFAULT_CONF" > "$CONF"

# ENV ENABLE_REGISTRATION false
# ENV REG_NOTIFY_ADDRESS changeme
# ENV REG_MAX_USERS 10
# ENV MYSQL_CHARSET 'UTF8'
# ENV FEED_CRYPT_KEY ''
# ENV SINGLE_USER_MODE false
# ENV SIMPLE_UPDATE_MODE false
# ENV LOCK_DIRECTORY 'lock'
# ENV CACHE_DIR 'cache'
# ENV ICONS_DIR "feed-icons"
# ENV ICONS_URL "feed-icons"
# ENV AUTH_AUTO_CREATE true
# ENV AUTH_AUTO_LOGIN true
# ENV FORCE_ARTICLE_PURGE 0
# ENV PUBSUBHUBBUB_HUB ''
# ENV PUBSUBHUBBUB_ENABLED false
# ENV SPHINX_SERVER 'localhost:9312'
# ENV SPHINX_INDEX 'ttrss, delta'
# ENV SESSION_COOKIE_LIFETIME 86400
# ENV SMTP_FROM_NAME 'Tiny Tiny RSS'
# ENV SMTP_FROM_ADDRESS 'noreply@your.domain.dom'
# ENV DIGEST_SUBJECT '[tt-rss] New headlines for last 24 hours'
# ENV SMTP_SERVER ''
# ENV SMTP_LOGIN ''
# ENV SMTP_PASSWORD ''
# ENV SMTP_SECURE ''
# ENV CHECK_FOR_UPDATES true
# ENV ENABLE_GZIP_OUTPUT false
# ENV PLUGINS 'auth_internal, note'
# ENV LOG_DESTINATION 'sql'